### ISSUE TITLE
Access or Roles requirement given to service account key for integration with DFCX #PermissionDenied #Roles

### ISSUE THREAD

**Issue by tima946** [GoogleCloudPlatform/dfcx-scrapi#103]
I got a service account key from my organization to make use of scrapi and automate some functionalities in DFCX like create bulk test cases and uploading intent with tp in bulk etc.
So the organization gave some access to that service account and when I use it to even read the agent using `get_agent()' it throws "PERMISSION DENIED" and basically says that my account doesn't have the right permission to perform this task without actually specifying which roles exactly.
I have less idea on what all roles/access the organization has given to the service account and I found no ways to find that unless I had access to IAM which I don't.
I would request to get clarity on what all roles does a service account need to perform basic functionalities like upload intents, create test cases etc.
I can see that in every example there is prerequisite to have "API admin role" assigned to the account but my organization can't provide me that access. So is that the issue or do we have some alternative roles that can compensate for it?
**Please make use of this link [https://cloud.google.com/dialogflow/cx/docs/concept/access-control](url)
and state exact roles needed in a service account to perform basic functionalities in DFCX.**

**Comment by kmaphoenix** [comment]
Hi @tima946 !

Authentication with Google APIs can be tricky at times, so I'll do my best to clarify a few scenarios below depending on how you are developing with the API.

# Roles and Permissions
The [IAM Roles](https://cloud.google.com/dialogflow/cx/docs/concept/access-control#iam-roles) required to make edits via the API contain the same underlying permissions that are granted to GCP principal accounts when editing via the UI/console. Depending on the tasks you want to accomplish via API, you will generally look to have 1 of these 3 roles granted:

_**TLDR: If you're planning on creating / updating resources, you need the Dialogflow API Admin role.**_

* _**Dialogflow API Admin**_ provides full read/write access via API. Note that if you are attempting to create new Intents, Pages, Flows, etc. using any create/update method, _this is the only set of permissions that allows you to do so_. 
* _**Dialogflow API Client**_ provides the ability to hold a conversation with your agent. This essentially the same as using the "Simulator" in the UI/Console. This permission _does not_ provide write access to Agent resources. You would only use this role if you're planning on testing out your agent by having a conversation via API. This could also be granted to any service account that was used for integration purposes. (i.e. Front End integration that needs to talk to the Dialogflow API back end.)
* _**Dialogflow API Reader**_ provides access to all GET methods from the API. If you're only planning on reading agent resources to see what they contain, this is the minimal permission needed to do so.

![image](https://user-images.githubusercontent.com/13949241/209211603-ebc85c88-0781-4339-97e5-82046168da24.png)

# Authentication Without Service Account
It's possible to do things via the API _without_ using a service account. However, you still need your principal GCP account to have the appropriate permissions to make changes via the API. This means you will need your IAM Administrator to assign one of the 3 Roles to your <username>@yourcompany.com account OR you can have your IAM Administrator grant you a [Basic GCP Role](https://cloud.google.com/iam/docs/understanding-roles#basic) like "Editor". The easy way to know if you have the right access is this: _If you can make edits and changes in the UI/Console with your principal account, you should be able to do the same via API using your principal account_.

## Google Colab Notebooks (.ipynb)
If you're using Google Colab notebooks for development, there's an easy way to test this out using the following code block.

```py
# Install SCRAPI
!pip install dfcx-scrapi==1.5.1 --quiet

# Assign your GCP Project ID to a variable for us with the auth chain below
project_id = 'YOUR_GCP_PROJECT'

# this will launch an interactive prompt that allows you to auth with GCP in a browser
!gcloud auth application-default login --no-launch-browser

# this will set your active project to the `project_id` above
!gcloud auth application-default set-quota-project $project_id

# You can use SCRAPI now without passing in auth creds
# The Colab environment will grab them based on the above auth chain

from dfcx_scrapi.core.intents import Intents

i = Intents()
agent_id = 'your_agent_id'
intents_map = i.get_intents_map(agent_id)
```

## Standard Python Environment (.py)
If you're working in an IDE like VS Code, you can perform the same auth chain above using `gcloud` commands. This will set an environment variable on your local machine that contains the authentication credentials that can be used with the API calls. Use the following code block from a local terminal (iTerm, VS Code Terminal, etc.) to set that up.

```bash
# Initialize gcloud if you haven't done this before
gcloud init

# Start the login process
gcloud auth login

# Check the auth list to see which user is currently logged in
gcloud auth list

# Set the GCP Project ID
gcloud config set project-id your_gcp_project_id
```

After doing the above auth chain, when you execute any .py script, it will attempt to use the environment credentials to pass to the API. You can test with this snippet of code in a .py file:

```py
from dfcx_scrapi.core.intents import Intents

def get_intents_map(agent_id):
  i = Intents()
  intents_map = i.get_intents_map(agent_id)

  return intents_map

if __name__ == "__main__":
  agent_id = 'your_agent_id'
  intents_map = get_intents_map(agent_id)

  print(intents_map)
```

# Summary
The key thing to remember is that no matter which method you choose to use from above, they will only work if either your Principal GCP Account or your Service Account has been granted the appropriate Roles / Permissions. If the default GCP Roles for Dialogflow are too broad, your IAM Administrator can choose to create a custom Role and assign individual permissions as needed.

Hope this helps.
I'll leave this Issue open for now to see if you have any other questions.

**Comment by kmaphoenix** [comment]
Closing issue based on previous answer.
