### ISSUE TITLE
list_agents function argument location_id has changed to location

### ISSUE THREAD

**Issue by xsgbloom** [GoogleCloudPlatform/dfcx-scrapi#138]
https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/1c9f81320ffb454718945f9caf47c27a0d72f232/src/dfcx_scrapi/core/agents.py#L89

This broke one of my customers in production. Underlying code uses parameter location_id. The documentation for this function still calls the argument "location_id", so I'm guessing this was an inadvertent change. Is there unit testing to catch/prevent this kind of thing?

**Comment by kmaphoenix** [comment]
@xsgbloom this was an inadvertent change.  
I will revert it back to the original.

Re: unit tests, unfortunately none are running on this file yet.  
We're in the process of building out unit tests for all files to prevent breaks like this from happening.
