### ISSUE TITLE
[FR] Add direct link to Colab in https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/main/examples/nlu_analysis_series/nlu_semantic_similarity_demo.ipynb

### ISSUE THREAD

**Issue by svet4** [GoogleCloudPlatform/dfcx-scrapi#150]
### Is your proposal related to a problem?

When I click on the Colab link in https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/main/examples/nlu_analysis_series/nlu_semantic_similarity_demo.ipynb, it opens a generic Google Colab page, and I have to paste a file link there.

### Describe the solution you'd like

Could you please add a link that would directly open https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/main/examples/nlu_analysis_series/nlu_semantic_similarity_demo.ipynb in Colab?

### Describe alternatives you've considered

Pasting the link manually.

### Additional context

It might be helpful to have it for other files too.

**Comment by kmaphoenix** [comment]
Updated all colabs to have 1-click links to launch directly.
Fixed in #181
