### ISSUE TITLE
[FR] Support endUserMetadata in detect_intent for Generative Agent 

### ISSUE THREAD

**Issue by ffeldhaus** [GoogleCloudPlatform/dfcx-scrapi#153]
### Is your proposal related to a problem?

[endUserMetadata](https://cloud.google.com/dialogflow/cx/docs/reference/rest/v3/QueryParameters) is used for [Personalization in Data store Agents](https://cloud.google.com/dialogflow/cx/docs/concept/data-store-agent#personalization).

### Describe the solution you'd like

The [`detect_intent` function](https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/37cf8cf7b2013a377740f68d8dcb7355632161e0/src/dfcx_scrapi/core/sessions.py#L190C17-L190C17) of the sessions class should allow specifying endUserMetadata.

**Comment by kmaphoenix** [comment]
Ref: https://github.com/googleapis/google-cloud-python/blob/main/packages/google-cloud-dialogflow-cx/google/cloud/dialogflowcx_v3/types/session.py#L919C9-L919C26

**Comment by jkshj21** [comment]
Hello, 

I worked on this feature. We can follow up on this branch below.

https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/912bb156da8dfd95de348f30a55c7b308d0ba0fd/src/dfcx_scrapi/core/sessions.py#L261

submitted a PR

**Comment by jkshj21** [comment]
In core.sessions.py, detect_intent now supports endUserMetadata. Can we close this ticket? @ffeldhaus

**Comment by ffeldhaus** [comment]
Looks good!
