### ISSUE TITLE
Playbook Instructions do not support writing sub-steps/indented steps

### ISSUE THREAD

**Issue by yashbadani-google** [GoogleCloudPlatform/dfcx-scrapi#206]
While creating a playbook, creating instructions require passing a list of strings which are converted to instruction steps. While this is helpful to add quick instructions, it does not provide an option to add sub-steps.

## Expected Behavior

For eg. Instructions
- If the user enquires about a product category:
   - Ask the user about the specific product name
   - Ask the user about their preferences ....

## Current Behavior
For eg. Instructions
- If the user enquires about a product category:
- Ask the user about the specific product name
- Ask the user about their preferences ....

## Possible Solution
Allow writing the `Step` object to `instructions` in create_playbook.

## Steps to Reproduce
Try by creating a copy of playbook and the instructions are not getting set correctly during create_playbook due to method requirements.

## Context (Environment)
We are trying to create a copy of playbook(with goals, instructions, examples and parameters) and saving it with a new name for internal tests and experimentations.

**Comment by kmaphoenix** [comment]
Fixed in #212 and #213
