### ISSUE TITLE
[BUG] _page_level_handlers() doesn't return df with all pages 

### ISSUE THREAD

**Issue by Greenford** [GoogleCloudPlatform/dfcx-scrapi#25]
## Expected Behavior

function returns dataframe for all pages in all flows within the agent

## Current Behavior

function returns a fraction of the expected pages. 

I wrote my own code to pull page event handlers before I was aware of find_event_handlers() (1/3 of which is _page_level_handlers) which returned EHs for 1379 for a certain agent. For the same agent, find_event_handlers() pulled EHs for only 77 pages.

**Comment by kmaphoenix** [comment]
@Greenford Ack.  

`search_util` is an outdated class and likely needs an overhaul as it was written with some pointed use cases in mind.   
If you have a patch for this please feel free to cut a branch and pick up the bug.

Adding link to code for later reference:
[find_event_handlers](https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/main/src/dfcx_scrapi/tools/search_util.py#L494)

**Comment by Greenford** [comment]
This bug report was mostly me incorrectly comparing 2 dataframes! The original function (now [page_level_handlers](https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/75acb1d993b2cb21234e102a0c80a817fd12a3c4/src/dfcx_scrapi/tools/search_util.py#L124) worked just fine. However, the previous flow_level_handlers returned a dataframe with duplicates. I also wrote more concise code that returns the same thing. 

This bug is resolved in [cleanup/search_util](https://github.com/GoogleCloudPlatform/dfcx-scrapi/tree/cleanup/search_util).

**Comment by kmaphoenix** [comment]
Closing. Resolved in PR #43 by @Greenford
