### ISSUE TITLE
[BUG] restore_agent should return a google.api_core.Operation

### ISSUE THREAD

**Issue by xsgbloom** [GoogleCloudPlatform/dfcx-scrapi#49]
https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/b25f2004c253a1b59c545346f0272f9a69ae83e9/src/dfcx_scrapi/core/agents.py#L396

When restore_agent returns a value, it should not be a str, it should be a google.api_core.Operation, which is the actual type of the response returned from line 422:

```        response = client.restore_agent(request)```

This is a call to Dialogflow CX v3beta1's client.restore_agent(), which returns a google.api_core.Operation object. When we return it as a string, we are essentially casting the Operation object to a string, so we trigger it's __str__() function and receive a string in the format 'projects/{project_id}/locations/{region_id}/operations/{operation_id}'

https://github.com/googleapis/python-dialogflow-cx/blob/main/google/cloud/dialogflowcx_v3beta1/services/agents/client.py#L1127

**Comment by xsgbloom** [comment]
@kmaphoenix - I'd like to take responsibility for fixing this issue. I'll need to discuss logistics with you.

For resolving this, I see these ways forward:
1. Do nothing, accept that restore_agent will just return a string of the operation_id
2. Remove the return type, so the function returns whatever type exists in the return value (the "lazy" way)
3. Declare the return type as google.api_core.Operation, which will require importing this type and adding google-api-core to the requirements.txt file, etc. (the not-lazy but very messy way)
4. Something not yet considered...

Do you have a leaning? I lean toward #3...

**Comment by kmaphoenix** [comment]
Each of the SCRAPI methods that return an LRO are returning a `string` to simplify checking the LRO object.  
SCRAPI has `Operations.get_lro` implemented to allow for this simplification of checking the status/contents of that object.

Example would be something like:
```
from dfcx_scrapi.core.agents import Agents
from dfcx_scrapi.core.operations import Operations

a = Agents()
o = Operations()

lro = a.export_agent(my_agent, 'gs://my_bucket/my_file.blob')

o.get_lro(lro)
```

PR #54 fixed some of the regionalization issues that had been reported as well.
