### ISSUE TITLE
[FR] <Replace utterance_generator.py model>

### ISSUE THREAD

**Issue by cgibson6279** [GoogleCloudPlatform/dfcx-scrapi#56]
### Problem

Pegasus models are developed by Google Research. The current model implemented in utterance_generator.py is a fine-tuned Pegasus model for paraphrasing that was fine-tuned external to Google. 

### Solution

Fine-tune a Pegasus model for paraphrasing tasks that will serve as a base model for SCRAPI.

**Comment by Greenford** [comment]
Status update: We were able to get training and evaluation to run to completion on a small subset(train[:1000], eval[:100]) of the PAWS dataset. How the resulting model performs compared to the current model in scrapi is unknown, but the current resulting model gives a [bleu](https://github.com/huggingface/datasets/tree/master/metrics/bleu) score of 0.62 on the evaluation subset (first 100 examples).
