### ISSUE TITLE
[FR] <Create Custom Model for Utterance Generation>

### ISSUE THREAD

**Issue by cgibson6279** [GoogleCloudPlatform/dfcx-scrapi#57]
### Problem

To make SCRAPI utterance generation more flexible, it would be worthwhile to supply users a function that will allow them to fine-tune their own custom Pegasus model for a given use case.  

### Solution

Reconfigure utterance_generator.py to set SCRAPI custom model as default, but provide a `create_pegasus_model` function that allows users to fine-tune a Pegasus-model on an existing or custom tensor flow dataset.

**Comment by Greenford** [comment]
@cgibson6279 Having been through a bit of the heartache that is training a model, is this issue still a goal? I'd be willing to provide the **compute instance configs, dependencies snapshot, and the notebook** we used, but... there's no way I'm going to guarantee it'll execute successfully a useful fraction of the time. 

@kmaphoenix can you give feedback about whether the above items should maybe stay Google-internal?

**Comment by cgibson6279** [comment]
Issue no longer relevant opening new ticket for custom model generation with pretrained-option
