### ISSUE TITLE
[FR] Examples for annotated TPs uploading

### ISSUE THREAD

**Issue by migoogle** [GoogleCloudPlatform/dfcx-scrapi#61]
### Is your proposal related to a problem?

It's related to understand on how to upload annotated TPs, how is the input file format and wich SCRAPI's resource I need to use to do that.

### Describe the solution you'd like

A notebook with some examples.

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by kmaphoenix** [comment]
@Greenford @cgibson6279 Can y'all take a look at this request and see if you have any notebooks or code snippets that would help guide a new user wanting to try this feature?

Perhaps we can include them in the examples folder as well.

**Comment by Greenford** [comment]
@migoogle can you take a look at the [bot_building_102 notebook and python file here?](https://github.com/lambertaurelle/dfcx-scrapi/tree/main/examples/bot_building_series) and let us know if that works? Or if there are gaps we should address, etc. 

@kmaphoenix There's already a pull request for it at [issue 45](https://github.com/GoogleCloudPlatform/dfcx-scrapi/pull/45)

**Comment by kmaphoenix** [comment]
Example included in PR #45
