### ISSUE TITLE
Importing Changelogs has an unresolved dependency on pandas

### ISSUE THREAD

**Issue by xsgbloom** [GoogleCloudPlatform/dfcx-scrapi#64]
from dfcx_scrapi.core.changelogs import Changelogs
  File ".../.local/lib/python3.9/site-packages/dfcx_scrapi/core/changelogs.py", line 20, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

Running ```pip3 install pandas``` resolves the issue. Need to check whether pandas is actually used in Changelogs. If so, we may need to add it to a requirements.txt?

**Comment by xsgbloom** [comment]
It's already there... https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/bff29c498f0d54701d651c2f99bcd51d4da5613c/requirements.txt#L6

Now I've gotta figure out why my system didn't install it when I installed dfcx-scrapi...

**Comment by MRyderOC** [comment]
I assume that you already created a virtual environment and activated it.
Try updating the pip before installing the requirements. That may solve your problem.

pip install --upgrade pip
pip install -r requirements.txt
