### ISSUE TITLE
[Pull Request] Agent Assist Class Addition

### ISSUE THREAD

**Issue by hkhaitan1** [GoogleCloudPlatform/dfcx-scrapi#71]
# Pull Request Template

## Description
The change aims to add modules in the test_cases class. This change will help the DDs & CAs get detailed information on test coverage rate with respect to intents, flows, transitions & route groups coverage. 

No new dependencies needs to be added or changed.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I extended the ScrapiBase class to create a new test_case_extend class. This was done to ensure that the module will integrate with the existing test cases class. Then I added the new modules as method to this class. 
I created a dummy agent in a GCP project and manually generated few test cases. I then used the agent id and a service account key from the above GCP project to test my code. The results were validated by matching the numbers in the DFCX console.

Requirements to run the above script-
- Agentid with some DFCX test cases configured
- SAK with Dialogflow test cases admin role

Please describe the tests that you ran to verify your changes. Provide instructions and code snippets so we can reproduce. Please also list any relevant details for your test configuration (i.e. new dependencies).

Psuedo Code- 

### Code Snippets:
```py
# Ex:
# from dfcx_scrapi.core.intents import Intents
# i = Intents()
# intents = i.list_intents()
# for intent in intents:
#   print(intent.display_name)
```

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code passes the linter as defined in the .pylintrc file
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

**Comment by kmaphoenix** [comment]
Hi @hkhaitan1 !

Can you please do the following:
1. Remove any links to internal resources, since this is a public facing repo.
2. Update the Title/Summary of this PR to reflect the contents of this change.

For [1], it's not necessary to provide the full details of your testing. You can instead describe your testing briefly without code or using pseudocode.

**Comment by hkhaitan1** [comment]
Edited the above comments. Please let me know if any more information is needed. Thanks

**Comment by kmaphoenix** [comment]
Issue/PR was originally related to Test case coverage, but the merged content was Agent Assist content only.
