### ISSUE TITLE
Pre-configured Issue and Pull Request Templates for this project

### ISSUE THREAD

**Issue by karkipra** [GoogleCloudPlatform/dfcx-scrapi#8]
## Background

I noticed that this repository does not have an issue template or PR template yet, so I was thinking of following these guides to create the respective templates. This can make writing bug reports, issues, PRs quicker and less ambiguous.

### Proposed solution

Issue Template:

- [Guide for Issue Templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
- Two types of issue templates:
  - Bug report [proposed template](https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/ISSUE_TEMPLATE.md)
  - Feature request [proposed template](https://github.com/wagtail/wagtail/issues/5560)
  - Alternatively, Github's default templates can also be used.
  
Pull Request Template:

- [Guide for PR templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [Proposed template](https://github.com/embeddedartistry/templates/blob/master/oss_docs/PULL_REQUEST_TEMPLATE.md)  

### Questions

- Should these templates be public or hidden?

**Comment by kmaphoenix** [comment]
Implemented the following templates for the project:
- Bug Report
- Feature Request
- Pull Request

![image](https://user-images.githubusercontent.com/13949241/147772114-db34607d-7f28-488b-a682-d3e10a99175f.png)

Thanks for the suggestion @karkipra !

Closing this Issue.
